architect:
  - ardesco
docker:
  image: "yegor256/rultor-image"
decrypt:
  settings.xml: "repo/settings.xml.asc"
  pubring.gpg: "repo/pubring.gpg.asc"
  secring.gpg: "repo/secring.gpg.asc"
release:
  pre: false
  script: |-
    mvn -Prelease versions:set "-DnewVersion=${tag}"
    export PATH=$JAVA_HOME/bin:$PATH
    git commit -am "${tag}"
    mvn clean deploy -Prelease --settings /home/r/settings.xml
  commanders:
    - ardesco
