architect:
  - ardesco
docker:
  image: "maven:3-jdk-7"
decrypt:
  settings.xml: "repo/settings.xml.asc"
  pubring.gpg: "repo/pubring.gpg.asc"
  secring.gpg: "repo/secring.gpg.asc"
release:
  script:
    - "sudo apt-get install gsettings-desktop-schemas -y"
    - "mvn versions:set -DnewVersion=${tag}"
    - "git commit -am ${tag}"
    - "mvn clean deploy --settings /home/r/settings.xml"