install: |-
  sudo apt-get install gsettings-desktop-schemas
architect:
  - ardesco
commander:
  - ardesco
decrypt:
  settings.xml: "repo/settings.xml.asc"
  pubring.gpg: "repo/pubring.gpg.asc"
  secring.gpg: "repo/secring.gpg.asc"
release:
  pre: false
  script: |-
    chmod 600 /home/r/pubring.gpg
    chmod 600 /home/r/secring.gpg
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Prelease --settings /home/r/settings.xml